version: "3"
services:

  mongo:
    container_name: sasstMongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: sasstServerApi
    restart: always
    depends_on:
      - mongo
    build: ./server
    ports:
      - "3000:3000"
    links:
      - mongo


  web:
    container_name: sasstServerWeb
    restart: always
    build: ./web
    ports: 
      - "8080:8080"
